# This is a basic workflow that is manually triggered

name: Checking compute usage

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron:  "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  running-jobs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Installing dependencies and running bust jobs and saving the logs for information 
      env:
        POLLY_USER_NAME: ${{ secrets.UserName }}
        POLLY_USER_PASSWORD: ${{ secrets.UserPassword }}
      run: |
        sudo npm install -g @elucidatainc/pollycli
        sudo cp ./patch/logs.js /usr/local/lib/node_modules/@elucidatainc/pollycli/src/logs.json
        sudo apt-get install expect
        echo '#!/usr/bin/expect -f' > login.sh
        echo 'set timeout -1' >> login.sh
        echo 'spawn polly login' >> login.sh
        echo 'expect "Enter user name:"' >> login.sh
        echo 'send -- "$env(POLLY_USER_NAME)\r"' >> login.sh
        echo 'expect "Enter password:"' >> login.sh
        echo 'send -- "$env(POLLY_USER_PASSWORD)\n"' >> login.sh
        echo 'expect eof' >> login.sh
        chmod +x ./login.sh
        ./login.sh
        rm ./login.sh
        sudo chmod +x ./run_all.sh
        ./run_all.sh
        git status
        git config --global user.email ${{ github.event.inputs.username }}
        git config --global user.name ${{ github.event.inputs.username }}
        git add -A
        pwd
        ls
        git commit -m "compute usage commit"
        git fetch origin master
        git push origin HEAD:master
